#以下这些类型会被忽略 目前支持修改:png/jpg/xib/sb/bundle/plist 类型资源
#这里只能加不能减少了,未来将支持更多
IgnoreFolderType:
  - a
  - framework
  - xcassets
  - appiconset
  - lproj
  - json
  - entitlements
  - xcodeproj

# -------------------------- 以下部分可以配置 ----------------------

#不处理的plist类型文件,不在该列表的plist将被处理
IgnorePlistList:
  - Info.plist
  - info.plist

#1.类相关
#1.1包含以下前缀的类都会被忽略
IgnoreClassPrefixList:
  - AF

#1.2以下类文件会被忽略
IgnoreClassNameList:
  - AppDelegate
  - ViewController

#1.3以下文件夹内的类会被忽略
#需要写忽略文件的上级文件夹,例如 x/y/z.h 就应该写y
IgnoreFolder:
  - AFNWorking

#1.4需要忽略的类属性
#类本身会被修改,类属性不会被修改,主要针对和网络交互的model类
IgnorePropertyOfClassList:
  - ""

#当前类名前缀
CurClassNamePrefix:
  - AES
  - AF
  - FM

#用来替换当前类前缀的前缀
ClassNamePrefix:
  - ""
ClassNameMinLen: 5
ClassNameMaxLen: 7

# 属性名前缀
PropertyPrefix:
  - ""
PropertyMinLen: 4
PropertyMaxLen: 6

# 方法名前缀
CurMethodNamePrefix:
  - april
MethodNamePrefix:
  - ""
MethodNameMinLen: 3
MethodNameMaxLen: 6

#如果是SDK,配置这个会在result.txt将需要暴露的头文件在最开始的位置展示出来
SDKHeader:
  - ""