# yaml语法说明

# 1.配置键值对
# 示例1.0 配置demo为hello
# demo: hello
# 示例1.1 配置demo为1
# demo: 1
# 示例1.2 配置demo2为nil(不能什么都不配置)
# demo: ""

# 2.配置数组
# 示例2.0 配置demo为["test1","test2"]
# demo:
# - test1
# - test2
# 示例2.1 配置demo4空数组(不能什么都不配置)
# demo4:
# - ""

# 3.配置复杂类型
# {"demo":"world","hello1":["world1","world2"]}
# demo:
#    hello: world
#    hello1:
#        - world1
#        - world2

# 以上是yaml语法说明配置说明
# ---------------------------------以下才是需要配置的内容---------------------------------
# #开头的是注释

# 混淆的时候不混淆@""这种字符串
IgnoreOCString: True

# 1.敏感词检测 可以自行添加
SensitiveWords:
  - zf
  - zfb
  - zhifubao
  - alipay
  - wx
  - wechat
  - weixin
  - pay
  - defray
  - disburse
  - buy
  - goumai
  - purchase
  - purchasing
  - order
  - dingdan
  - goods
  - salad
  - libao
  - gift
  - hongbao
  - diamond
  - ingots
  - money
  - show
  - hidden
  - platform
  - sdk
  - bugly
  - qq
  - hot
  - jine
  - 微信
  - 支付宝
  - 银联
  - 支付
  - 充值
  - 交易
  - 购
  - 买
  - 内购
  - 商品
  - 兑换
  - 礼包
  - 开关
  - 订单
  - 下单
  - 金额
  - 元
  - ¥
  - $

# 2.字符串差异化比例(0到1之间的小数)
# http(s)开头的链接一定会被处理的
# "0.5"表示字符串混淆50%
# "1"表示字符串混淆100%
StringDifferPercent: "1"

# 3.类相关
# 3.1 类白名单(白名单中的类不会被修改)
# 假设 AppDelegate类需要忽略,配置如下即可
# - AppDelegate
# AppDelegate.h 和AppDelegate.m文件中自身的方法和属性等符号都不会被修改
# AppDelegate.h 和AppDelegate.m文件中引用的类和调用的外部方法等会被修改
# 如果需要忽略.a静态库对应的头文件,需要将对应的头文件配置在下面
IgnoreClassList:
  - AppDelegate
  - ViewController
  - SceneDelegate

# 3.2 文件夹白名单(文件夹中的文件不会被修改)
# 例如 x/y/z.h
# - x #忽略x文件夹下所有类型的文件和文件夹
# - y #忽略y文件夹下所有类型的文件和文件夹
IgnoreFolder:
  - Test
  - ThirdLib
  - ThirdFrameWork
  - Supporting Files
  - igonreFolder

# 3.3 属性白名单(对应的类属性不会修改)
# 以下的类 属性不会被修改,类名、方法等其他都会修改,主要针对和网络交互的model类
IgnorePropertyOfClassList:
  - ""

# 4.前缀相关

# 4.1类前缀 当前类名前缀集合
# 如果项目中的资源文件或者类文件有特殊的前缀,可以通过这里移除或者替换
# 例如 项目中有XXHello类 配置 XX: YY 意思是用YY替换XX
# 例如 项目中有XXHello类 配置 XX: "" 意思是用空白替换XX,也就是移除XX
# NeedDifferClassNamePrefix:
#   XX:
#       - YY
#       - YYZ
#   iOS: andorid
# 意思是用YY/YYZ随机替换XX
# 意思是用andorid随机替换iOS
# 可自行按照格式无限制添加
# 如果没有需要处理的,配置如下
# NeedDifferClassNamePrefix:
# "": ""

NeedDifferClassNamePrefix:
  "": ""

# 4.2 属性名前缀
# 如果项目中有属性包含特殊的前缀,可以通过这里移除或者替换
# 规则同NeedDifferClassNamePrefix
NeedDifferPropertyPrefix:
  "": ""

# 4.3 方法名前缀
# 如果项目中有方法包含特殊的前缀,可以通过这里移除或者替换
# 规则同NeedDifferClassNamePrefix
NeedDifferMethodPrefix:
  "": ""

# 4.4 枚举前缀
# 如果项目中有枚举包含特殊的前缀,可以通过这里移除或者替换
# 规则同NeedDifferClassNamePrefix
NeedDifferEnumPrefix:
  "": ""

# 5.需要暴露的头文件(方便SDK)
SDKHeader:
  - ""
